//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChessTournamentManager.LanguageAssets.TournamentForParticipants {
    using System;
    
    
    /// <summary>
    ///   Třída prostředků se silnými typy pro vyhledávání lokalizovaných řetězců atp.
    /// </summary>
    // Tato třída byla automaticky generována třídou StronglyTypedResourceBuilder
    // pomocí nástroje podobného aplikaci ResGen nebo Visual Studio.
    // Chcete-li přidat nebo odebrat člena, upravte souboru .ResX a pak znovu spusťte aplikaci ResGen
    // s parametrem /str nebo znovu sestavte projekt aplikace Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TournamentForParticipantsLabels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TournamentForParticipantsLabels() {
        }
        
        /// <summary>
        ///   Vrací instanci ResourceManager uloženou v mezipaměti použitou touto třídou.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChessTournamentManager.LanguageAssets.TournamentForParticipants.TournamentForPart" +
                            "icipantsLabels", typeof(TournamentForParticipantsLabels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Potlačí vlastnost CurrentUICulture aktuálního vlákna pro všechna
        ///   vyhledání prostředků pomocí třídy prostředků se silnými typy.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Mark tournament as favourite.
        /// </summary>
        public static string mainMarkTournamentAsFavourite {
            get {
                return ResourceManager.GetString("mainMarkTournamentAsFavourite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný This tournament does not exist.
        /// </summary>
        public static string mainNotExistingTournament {
            get {
                return ResourceManager.GetString("mainNotExistingTournament", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Round draws.
        /// </summary>
        public static string mainTabsDraws {
            get {
                return ResourceManager.GetString("mainTabsDraws", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Players.
        /// </summary>
        public static string mainTabsPlayers {
            get {
                return ResourceManager.GetString("mainTabsPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Preposition.
        /// </summary>
        public static string mainTabsPreposition {
            get {
                return ResourceManager.GetString("mainTabsPreposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Results.
        /// </summary>
        public static string mainTabsResults {
            get {
                return ResourceManager.GetString("mainTabsResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Teams.
        /// </summary>
        public static string mainTabsTeams {
            get {
                return ResourceManager.GetString("mainTabsTeams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Unmark tournament as favourite.
        /// </summary>
        public static string mainUnmarkTournamentAsFavourite {
            get {
                return ResourceManager.GetString("mainUnmarkTournamentAsFavourite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Location.
        /// </summary>
        public static string prepositionAddress {
            get {
                return ResourceManager.GetString("prepositionAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Date.
        /// </summary>
        public static string prepositionDate {
            get {
                return ResourceManager.GetString("prepositionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Round pairing.
        /// </summary>
        public static string prepositionDrawType {
            get {
                return ResourceManager.GetString("prepositionDrawType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný End date.
        /// </summary>
        public static string prepositionEndDate {
            get {
                return ResourceManager.GetString("prepositionEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Expected number of rounds.
        /// </summary>
        public static string prepositionExpectedNumberOfRounds {
            get {
                return ResourceManager.GetString("prepositionExpectedNumberOfRounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Maximum number of players.
        /// </summary>
        public static string prepositionMaximumNumberOfPlayers {
            get {
                return ResourceManager.GetString("prepositionMaximumNumberOfPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Maximum number of teams.
        /// </summary>
        public static string prepositionMaximumNumberOfTeams {
            get {
                return ResourceManager.GetString("prepositionMaximumNumberOfTeams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Number of registered players.
        /// </summary>
        public static string prepositionNumberOfRegisteredPlayers {
            get {
                return ResourceManager.GetString("prepositionNumberOfRegisteredPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Number of registered teams.
        /// </summary>
        public static string prepositionNumberOfRegisteredTeams {
            get {
                return ResourceManager.GetString("prepositionNumberOfRegisteredTeams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Registration close on.
        /// </summary>
        public static string prepositionRegistrationClosed {
            get {
                return ResourceManager.GetString("prepositionRegistrationClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Registration opened from.
        /// </summary>
        public static string prepositionRegistrationOpened {
            get {
                return ResourceManager.GetString("prepositionRegistrationOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Start date.
        /// </summary>
        public static string prepositionStartDate {
            get {
                return ResourceManager.GetString("prepositionStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Team size.
        /// </summary>
        public static string prepositionTeamSize {
            get {
                return ResourceManager.GetString("prepositionTeamSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Team tournament.
        /// </summary>
        public static string prepositionTeamTournament {
            get {
                return ResourceManager.GetString("prepositionTeamTournament", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Time control.
        /// </summary>
        public static string prepositionTimeControl {
            get {
                return ResourceManager.GetString("prepositionTimeControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný From move.
        /// </summary>
        public static string prepositionTimeControlFromMove {
            get {
                return ResourceManager.GetString("prepositionTimeControlFromMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný per move.
        /// </summary>
        public static string prepositionTimeControlPerMove {
            get {
                return ResourceManager.GetString("prepositionTimeControlPerMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Time control type.
        /// </summary>
        public static string prepositionTimeControlType {
            get {
                return ResourceManager.GetString("prepositionTimeControlType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Tournament prepositions.
        /// </summary>
        public static string prepositionTitle {
            get {
                return ResourceManager.GetString("prepositionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Cannot load the tournament, please try it later.
        /// </summary>
        public static string prepositionTournamentCannotLoad {
            get {
                return ResourceManager.GetString("prepositionTournamentCannotLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Description.
        /// </summary>
        public static string prepositionTournamentDescription {
            get {
                return ResourceManager.GetString("prepositionTournamentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Tournament name.
        /// </summary>
        public static string prepositionTournamentName {
            get {
                return ResourceManager.GetString("prepositionTournamentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Tournament information.
        /// </summary>
        public static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
