//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChessTournamentManager.LanguageAssets.TournamentManagementLabels {
    using System;
    
    
    /// <summary>
    ///   Třída prostředků se silnými typy pro vyhledávání lokalizovaných řetězců atp.
    /// </summary>
    // Tato třída byla automaticky generována třídou StronglyTypedResourceBuilder
    // pomocí nástroje podobného aplikaci ResGen nebo Visual Studio.
    // Chcete-li přidat nebo odebrat člena, upravte souboru .ResX a pak znovu spusťte aplikaci ResGen
    // s parametrem /str nebo znovu sestavte projekt aplikace Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TournamentManagementLabels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TournamentManagementLabels() {
        }
        
        /// <summary>
        ///   Vrací instanci ResourceManager uloženou v mezipaměti použitou touto třídou.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChessTournamentManager.LanguageAssets.TournamentManagementLabels.TournamentManage" +
                            "mentLabels", typeof(TournamentManagementLabels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Potlačí vlastnost CurrentUICulture aktuálního vlákna pro všechna
        ///   vyhledání prostředků pomocí třídy prostředků se silnými typy.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Played as black.
        /// </summary>
        public static string BlackPiecesPlayed {
            get {
                return ResourceManager.GetString("BlackPiecesPlayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Buchholz.
        /// </summary>
        public static string Buchholz {
            get {
                return ResourceManager.GetString("Buchholz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Bucholz shortened.
        /// </summary>
        public static string BuchholzShortened {
            get {
                return ResourceManager.GetString("BuchholzShortened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Cancel changes.
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Error has occured, please try it later.
        /// </summary>
        public static string databaseCannotConnect {
            get {
                return ResourceManager.GetString("databaseCannotConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Back to managed tournaments.
        /// </summary>
        public static string mainPageBackToManagedTournamentsButton {
            get {
                return ResourceManager.GetString("mainPageBackToManagedTournamentsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Error occured during deletion of the tournament, please try it later.
        /// </summary>
        public static string mainPageCannotDeleteTournamentError {
            get {
                return ResourceManager.GetString("mainPageCannotDeleteTournamentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Error occured during starting the tournament, please try it later.
        /// </summary>
        public static string mainPageCannotStartTournamentError {
            get {
                return ResourceManager.GetString("mainPageCannotStartTournamentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Delete tournament.
        /// </summary>
        public static string mainPageDeleteTournamentButton {
            get {
                return ResourceManager.GetString("mainPageDeleteTournamentButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Are you sure you want to delete this tournament? This action is not reversible.
        /// </summary>
        public static string mainPageDeleteTournamentDialogDescription {
            get {
                return ResourceManager.GetString("mainPageDeleteTournamentDialogDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Delete tournament.
        /// </summary>
        public static string mainPageDeleteTournamentDialogHeader {
            get {
                return ResourceManager.GetString("mainPageDeleteTournamentDialogHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný No.
        /// </summary>
        public static string mainPageDeleteTournamentDialogNo {
            get {
                return ResourceManager.GetString("mainPageDeleteTournamentDialogNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Yes.
        /// </summary>
        public static string mainPageDeleteTournamentDialogYes {
            get {
                return ResourceManager.GetString("mainPageDeleteTournamentDialogYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný You are not a manager of this tournament. You cannot edit it..
        /// </summary>
        public static string mainPageNotAManager {
            get {
                return ResourceManager.GetString("mainPageNotAManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Start tournament.
        /// </summary>
        public static string mainPageStartTournamentButton {
            get {
                return ResourceManager.GetString("mainPageStartTournamentButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Round draws.
        /// </summary>
        public static string mainPageTabDraws {
            get {
                return ResourceManager.GetString("mainPageTabDraws", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Registered players.
        /// </summary>
        public static string mainPageTabRegisteredPlayers {
            get {
                return ResourceManager.GetString("mainPageTabRegisteredPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Registered teams.
        /// </summary>
        public static string mainPageTabRegisteredTeams {
            get {
                return ResourceManager.GetString("mainPageTabRegisteredTeams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Register player.
        /// </summary>
        public static string mainPageTabRegisterPlayer {
            get {
                return ResourceManager.GetString("mainPageTabRegisterPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Results.
        /// </summary>
        public static string mainPageTabResults {
            get {
                return ResourceManager.GetString("mainPageTabResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Settings.
        /// </summary>
        public static string mainPageTabSettings {
            get {
                return ResourceManager.GetString("mainPageTabSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Managed tournaments.
        /// </summary>
        public static string mainPageTitle {
            get {
                return ResourceManager.GetString("mainPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Managed tournaments.
        /// </summary>
        public static string managedTournamentsTitle {
            get {
                return ResourceManager.GetString("managedTournamentsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Here are all tournaments which you manage. By clicking on manage button you will be forwarded to page where you can manage specific tournament.
        /// </summary>
        public static string managedTournamentsTooltip {
            get {
                return ResourceManager.GetString("managedTournamentsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný No managed tournaments were found.
        /// </summary>
        public static string noManagedTournamentsWereFound {
            get {
                return ResourceManager.GetString("noManagedTournamentsWereFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Selected tournament does not exist..
        /// </summary>
        public static string performaceInvalidTournament {
            get {
                return ResourceManager.GetString("performaceInvalidTournament", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Opponent.
        /// </summary>
        public static string performanceAgainst {
            get {
                return ResourceManager.GetString("performanceAgainst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Color.
        /// </summary>
        public static string performanceColor {
            get {
                return ResourceManager.GetString("performanceColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Performance of player: .
        /// </summary>
        public static string performanceForPlayer {
            get {
                return ResourceManager.GetString("performanceForPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Result.
        /// </summary>
        public static string performanceResult {
            get {
                return ResourceManager.GetString("performanceResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Player performance.
        /// </summary>
        public static string performanceTitle {
            get {
                return ResourceManager.GetString("performanceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Cannot get players from database, please try it later.
        /// </summary>
        public static string registeredPlayersCannotGetPlayersFromDatabase {
            get {
                return ResourceManager.GetString("registeredPlayersCannotGetPlayersFromDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Players were removed from tournament.
        /// </summary>
        public static string registeredPlayersDeleteConfirmation {
            get {
                return ResourceManager.GetString("registeredPlayersDeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný First name.
        /// </summary>
        public static string registeredPlayersFirstName {
            get {
                return ResourceManager.GetString("registeredPlayersFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Last name.
        /// </summary>
        public static string registeredPlayersLastName {
            get {
                return ResourceManager.GetString("registeredPlayersLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný There are no registered players.
        /// </summary>
        public static string registeredPlayersNoPlayers {
            get {
                return ResourceManager.GetString("registeredPlayersNoPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Number of registered players:.
        /// </summary>
        public static string registeredPlayersNumberOfRegisteredPlayers {
            get {
                return ResourceManager.GetString("registeredPlayersNumberOfRegisteredPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Cannot get teams from database, please try it later.
        /// </summary>
        public static string registeredTeamsDatabaseError {
            get {
                return ResourceManager.GetString("registeredTeamsDatabaseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Teams were removed from tournament.
        /// </summary>
        public static string registeredTeamsDeleteConfirmation {
            get {
                return ResourceManager.GetString("registeredTeamsDeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný There are no registered teams.
        /// </summary>
        public static string registeredTeamsNoRegisteredTeams {
            get {
                return ResourceManager.GetString("registeredTeamsNoRegisteredTeams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Chess club:.
        /// </summary>
        public static string registerUnknownPlayerChessClub {
            get {
                return ResourceManager.GetString("registerUnknownPlayerChessClub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Cannot register new player, please try it later.
        /// </summary>
        public static string registerUnknownPlayerDatabaseError {
            get {
                return ResourceManager.GetString("registerUnknownPlayerDatabaseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Player.
        /// </summary>
        public static string registerUnknownPlayerDatabaseSuccessPart1 {
            get {
                return ResourceManager.GetString("registerUnknownPlayerDatabaseSuccessPart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný was registered to tournament.
        /// </summary>
        public static string registerUnknownPlayerDatabaseSuccessPart2 {
            get {
                return ResourceManager.GetString("registerUnknownPlayerDatabaseSuccessPart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Elo:.
        /// </summary>
        public static string registerUnknownPlayerElo {
            get {
                return ResourceManager.GetString("registerUnknownPlayerElo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný First name:.
        /// </summary>
        public static string registerUnknownPlayerFirstName {
            get {
                return ResourceManager.GetString("registerUnknownPlayerFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Last name:.
        /// </summary>
        public static string registerUnknownPlayerLastName {
            get {
                return ResourceManager.GetString("registerUnknownPlayerLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Middle name:.
        /// </summary>
        public static string registerUnknownPlayerMiddleName {
            get {
                return ResourceManager.GetString("registerUnknownPlayerMiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Register player.
        /// </summary>
        public static string registerUnknownPlayerRegisterPlayerButton {
            get {
                return ResourceManager.GetString("registerUnknownPlayerRegisterPlayerButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Name.
        /// </summary>
        public static string resultsCurrentStandingsName {
            get {
                return ResourceManager.GetString("resultsCurrentStandingsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Place.
        /// </summary>
        public static string resultsCurrentStandingsPlace {
            get {
                return ResourceManager.GetString("resultsCurrentStandingsPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Score.
        /// </summary>
        public static string resultsCurrentStandingsScore {
            get {
                return ResourceManager.GetString("resultsCurrentStandingsScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Show graphical representation.
        /// </summary>
        public static string resultsShowGraphicalRepresentationSwitch {
            get {
                return ResourceManager.GetString("resultsShowGraphicalRepresentationSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Next round.
        /// </summary>
        public static string roundDrawNextRound {
            get {
                return ResourceManager.GetString("roundDrawNextRound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Save.
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný City:.
        /// </summary>
        public static string settingsTabAddressCity {
            get {
                return ResourceManager.GetString("settingsTabAddressCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Country:.
        /// </summary>
        public static string settingsTabAddressCountry {
            get {
                return ResourceManager.GetString("settingsTabAddressCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný House number:.
        /// </summary>
        public static string settingsTabAddressHouseNumber {
            get {
                return ResourceManager.GetString("settingsTabAddressHouseNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Save.
        /// </summary>
        public static string settingsTabAddressSaveButton {
            get {
                return ResourceManager.GetString("settingsTabAddressSaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Street:.
        /// </summary>
        public static string settingsTabAddressStreet {
            get {
                return ResourceManager.GetString("settingsTabAddressStreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný ZIP:.
        /// </summary>
        public static string settingsTabAddressZip {
            get {
                return ResourceManager.GetString("settingsTabAddressZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Location.
        /// </summary>
        public static string settingsTabLocation {
            get {
                return ResourceManager.GetString("settingsTabLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Registration.
        /// </summary>
        public static string settingsTabRegistration {
            get {
                return ResourceManager.GetString("settingsTabRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Maximum number of participants.
        /// </summary>
        public static string settingsTabRegistrationMaximumNumberOfParticipants {
            get {
                return ResourceManager.GetString("settingsTabRegistrationMaximumNumberOfParticipants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Registration opened from.
        /// </summary>
        public static string settingsTabRegistrationRegistrationFrom {
            get {
                return ResourceManager.GetString("settingsTabRegistrationRegistrationFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Registration closed at.
        /// </summary>
        public static string settingsTabRegistrationRegistrationTo {
            get {
                return ResourceManager.GetString("settingsTabRegistrationRegistrationTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Save.
        /// </summary>
        public static string settingsTabRegistrationSaveButton {
            get {
                return ResourceManager.GetString("settingsTabRegistrationSaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Results.
        /// </summary>
        public static string settingsTabResults {
            get {
                return ResourceManager.GetString("settingsTabResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Number of points for draw.
        /// </summary>
        public static string settingsTabResultsSettingsPointsPerDraw {
            get {
                return ResourceManager.GetString("settingsTabResultsSettingsPointsPerDraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Number of points for win.
        /// </summary>
        public static string settingsTabResultsSettingsPointsPerWin {
            get {
                return ResourceManager.GetString("settingsTabResultsSettingsPointsPerWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Calculate by points per win/draw.
        /// </summary>
        public static string settingsTabResultsSettingsPointsPerWinOrNot {
            get {
                return ResourceManager.GetString("settingsTabResultsSettingsPointsPerWinOrNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Save.
        /// </summary>
        public static string settingsTabResultsSettingsSaveButton {
            get {
                return ResourceManager.GetString("settingsTabResultsSettingsSaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Save.
        /// </summary>
        public static string settingsTabSwissSave {
            get {
                return ResourceManager.GetString("settingsTabSwissSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Swiss settings.
        /// </summary>
        public static string settingsTabSwissSettings {
            get {
                return ResourceManager.GetString("settingsTabSwissSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Save.
        /// </summary>
        public static string settingsTabSwissSettingsSaveButton {
            get {
                return ResourceManager.GetString("settingsTabSwissSettingsSaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Team settings.
        /// </summary>
        public static string settingsTabTeamSettings {
            get {
                return ResourceManager.GetString("settingsTabTeamSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný You cannot edit team size if a team is already registered.
        /// </summary>
        public static string settingsTabTeamSettingsCannotEdit {
            get {
                return ResourceManager.GetString("settingsTabTeamSettingsCannotEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Save.
        /// </summary>
        public static string settingsTabTeamSettingsSaveButton {
            get {
                return ResourceManager.GetString("settingsTabTeamSettingsSaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Number of players in teams:.
        /// </summary>
        public static string settingsTabTeamSettingsTeamSize {
            get {
                return ResourceManager.GetString("settingsTabTeamSettingsTeamSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Time control.
        /// </summary>
        public static string settingsTabTimeControl {
            get {
                return ResourceManager.GetString("settingsTabTimeControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný From move:.
        /// </summary>
        public static string settingsTabTimeControlFromMove {
            get {
                return ResourceManager.GetString("settingsTabTimeControlFromMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Hours:.
        /// </summary>
        public static string settingsTabTimeControlHours {
            get {
                return ResourceManager.GetString("settingsTabTimeControlHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Increment (s).
        /// </summary>
        public static string settingsTabTimeControlIncrement {
            get {
                return ResourceManager.GetString("settingsTabTimeControlIncrement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Minutes:.
        /// </summary>
        public static string settingsTabTimeControlMinutes {
            get {
                return ResourceManager.GetString("settingsTabTimeControlMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Save.
        /// </summary>
        public static string settingsTabTimeControlSaveButton {
            get {
                return ResourceManager.GetString("settingsTabTimeControlSaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Seconds:.
        /// </summary>
        public static string settingsTabTimeControlSeconds {
            get {
                return ResourceManager.GetString("settingsTabTimeControlSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Main picture.
        /// </summary>
        public static string settingsTabTournamentMainPicture {
            get {
                return ResourceManager.GetString("settingsTabTournamentMainPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Black.
        /// </summary>
        public static string singlePlayerDrawBlack {
            get {
                return ResourceManager.GetString("singlePlayerDrawBlack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Generate this round.
        /// </summary>
        public static string singlePlayerDrawGenerateRoundButton {
            get {
                return ResourceManager.GetString("singlePlayerDrawGenerateRoundButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný This round draw was not yet generated.
        /// </summary>
        public static string singlePlayerDrawNotGeneratedInfo {
            get {
                return ResourceManager.GetString("singlePlayerDrawNotGeneratedInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Round number:.
        /// </summary>
        public static string singlePlayerDrawRoundNumberInfoPart1 {
            get {
                return ResourceManager.GetString("singlePlayerDrawRoundNumberInfoPart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný of.
        /// </summary>
        public static string singlePlayerDrawRoundNumberInfoPart2 {
            get {
                return ResourceManager.GetString("singlePlayerDrawRoundNumberInfoPart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Save match results.
        /// </summary>
        public static string singlePlayerDrawSaveMatchResultsButton {
            get {
                return ResourceManager.GetString("singlePlayerDrawSaveMatchResultsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný White.
        /// </summary>
        public static string singlePlayerDrawWhite {
            get {
                return ResourceManager.GetString("singlePlayerDrawWhite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Sonnenborn-Berger.
        /// </summary>
        public static string SonnenbornBerger {
            get {
                return ResourceManager.GetString("SonnenbornBerger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Tournament contains less than 2 players, tournament cannot be started with count.
        /// </summary>
        public static string startTournamentSingleNotEnough {
            get {
                return ResourceManager.GetString("startTournamentSingleNotEnough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Tournament was started.
        /// </summary>
        public static string startTournamentStarted {
            get {
                return ResourceManager.GetString("startTournamentStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Tournament contains less than 2 teams, tournament cannot be started with this count.
        /// </summary>
        public static string startTournamentTeamNotEnough {
            get {
                return ResourceManager.GetString("startTournamentTeamNotEnough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Generate this round.
        /// </summary>
        public static string teamDrawGenerateRoundButton {
            get {
                return ResourceManager.GetString("teamDrawGenerateRoundButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný This round draw was not yet generated.
        /// </summary>
        public static string teamDrawNotGeneratedInfo {
            get {
                return ResourceManager.GetString("teamDrawNotGeneratedInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Black.
        /// </summary>
        public static string teamDrawTieBreakBlack {
            get {
                return ResourceManager.GetString("teamDrawTieBreakBlack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný White.
        /// </summary>
        public static string teamDrawTieBreakWhite {
            get {
                return ResourceManager.GetString("teamDrawTieBreakWhite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Tiebreak winner:.
        /// </summary>
        public static string teamDrawTieBreakWinner {
            get {
                return ResourceManager.GetString("teamDrawTieBreakWinner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Invalid format, please use: .
        /// </summary>
        public static string uploadPictureFormInvalidFormat {
            get {
                return ResourceManager.GetString("uploadPictureFormInvalidFormat", resourceCulture);
            }
        }
    }
}
