//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChessTournamentManager.LanguageAssets.Profiles {
    using System;
    
    
    /// <summary>
    ///   Třída prostředků se silnými typy pro vyhledávání lokalizovaných řetězců atp.
    /// </summary>
    // Tato třída byla automaticky generována třídou StronglyTypedResourceBuilder
    // pomocí nástroje podobného aplikaci ResGen nebo Visual Studio.
    // Chcete-li přidat nebo odebrat člena, upravte souboru .ResX a pak znovu spusťte aplikaci ResGen
    // s parametrem /str nebo znovu sestavte projekt aplikace Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ProfilesLabels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProfilesLabels() {
        }
        
        /// <summary>
        ///   Vrací instanci ResourceManager uloženou v mezipaměti použitou touto třídou.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChessTournamentManager.LanguageAssets.Profiles.ProfilesLabels", typeof(ProfilesLabels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Potlačí vlastnost CurrentUICulture aktuálního vlákna pro všechna
        ///   vyhledání prostředků pomocí třídy prostředků se silnými typy.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Edit profile.
        /// </summary>
        public static string accountEditProfileButton {
            get {
                return ResourceManager.GetString("accountEditProfileButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný You can see your own profile as other people can see it. After clicking on Edit button you will be forwarded to page where it is possible to modify this information and upload your profile picture if you want.
        /// </summary>
        public static string accountTooltip {
            get {
                return ResourceManager.GetString("accountTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný You profile does not exist, create it using button above.
        /// </summary>
        public static string acountDoesNotExist {
            get {
                return ResourceManager.GetString("acountDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Back to profile.
        /// </summary>
        public static string formBackToProfileButton {
            get {
                return ResourceManager.GetString("formBackToProfileButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Profile cannot be loaded, please try it later.
        /// </summary>
        public static string formCannotBeLoadedError {
            get {
                return ResourceManager.GetString("formCannotBeLoadedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Profile cannot be saved, please try it later.
        /// </summary>
        public static string formCannotBeSavedError {
            get {
                return ResourceManager.GetString("formCannotBeSavedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Chess club:.
        /// </summary>
        public static string formClub {
            get {
                return ResourceManager.GetString("formClub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Country:.
        /// </summary>
        public static string formCountry {
            get {
                return ResourceManager.GetString("formCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Date of birth:.
        /// </summary>
        public static string formDateOfBirth {
            get {
                return ResourceManager.GetString("formDateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Elo:.
        /// </summary>
        public static string formElo {
            get {
                return ResourceManager.GetString("formElo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný FIDE ID:.
        /// </summary>
        public static string formFideId {
            get {
                return ResourceManager.GetString("formFideId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný First name:.
        /// </summary>
        public static string formFirstName {
            get {
                return ResourceManager.GetString("formFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Last name:.
        /// </summary>
        public static string formLastName {
            get {
                return ResourceManager.GetString("formLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Middle name:.
        /// </summary>
        public static string formMiddleName {
            get {
                return ResourceManager.GetString("formMiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Your profile picture.
        /// </summary>
        public static string formProfilePictureHeading {
            get {
                return ResourceManager.GetString("formProfilePictureHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Save.
        /// </summary>
        public static string formSaveButton {
            get {
                return ResourceManager.GetString("formSaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Edit profile.
        /// </summary>
        public static string formTitle {
            get {
                return ResourceManager.GetString("formTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Here you can edit your personal information. These information are publicly visible. Players and organizers then can get information about you, see your results, tournaments... You can also upload profile picture which will be visible as a main picture on your profile page.
        /// </summary>
        public static string formTooltip {
            get {
                return ResourceManager.GetString("formTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Profile was saved.
        /// </summary>
        public static string formWasSaved {
            get {
                return ResourceManager.GetString("formWasSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný My profile.
        /// </summary>
        public static string myProfileTitle {
            get {
                return ResourceManager.GetString("myProfileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný No tournaments related to this player.
        /// </summary>
        public static string noTournaments {
            get {
                return ResourceManager.GetString("noTournaments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Cannot get profile information, please try it later.
        /// </summary>
        public static string profileCannotLoad {
            get {
                return ResourceManager.GetString("profileCannotLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Chess club.
        /// </summary>
        public static string profileClub {
            get {
                return ResourceManager.GetString("profileClub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Country.
        /// </summary>
        public static string profileCountry {
            get {
                return ResourceManager.GetString("profileCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Date of birth.
        /// </summary>
        public static string profileDateOfBirth {
            get {
                return ResourceManager.GetString("profileDateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Elo.
        /// </summary>
        public static string profileElo {
            get {
                return ResourceManager.GetString("profileElo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný FIDE ID.
        /// </summary>
        public static string profileFideId {
            get {
                return ResourceManager.GetString("profileFideId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Profile information are currently not in database.
        /// </summary>
        public static string profileNotExistsInDatabase {
            get {
                return ResourceManager.GetString("profileNotExistsInDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Profiles.
        /// </summary>
        public static string profileTitle {
            get {
                return ResourceManager.GetString("profileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Here you can see profile of a player with personal information and tournaments he/she attended.
        /// </summary>
        public static string profileTooltip {
            get {
                return ResourceManager.GetString("profileTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Profile.
        /// </summary>
        public static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
    }
}
