//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChessTournamentManager.LanguageAssets.TeamManagement {
    using System;
    
    
    /// <summary>
    ///   Třída prostředků se silnými typy pro vyhledávání lokalizovaných řetězců atp.
    /// </summary>
    // Tato třída byla automaticky generována třídou StronglyTypedResourceBuilder
    // pomocí nástroje podobného aplikaci ResGen nebo Visual Studio.
    // Chcete-li přidat nebo odebrat člena, upravte souboru .ResX a pak znovu spusťte aplikaci ResGen
    // s parametrem /str nebo znovu sestavte projekt aplikace Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TeamManagementLabels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TeamManagementLabels() {
        }
        
        /// <summary>
        ///   Vrací instanci ResourceManager uloženou v mezipaměti použitou touto třídou.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChessTournamentManager.LanguageAssets.TeamManagement.TeamManagementLabels", typeof(TeamManagementLabels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Potlačí vlastnost CurrentUICulture aktuálního vlákna pro všechna
        ///   vyhledání prostředků pomocí třídy prostředků se silnými typy.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný You can modify this team.
        /// </summary>
        public static string canModifyTeam {
            get {
                return ResourceManager.GetString("canModifyTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný You cannot modify team, because it is already registered to tournament.
        /// </summary>
        public static string cannotModifyRegisteredToTournament {
            get {
                return ResourceManager.GetString("cannotModifyRegisteredToTournament", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Create new team.
        /// </summary>
        public static string createNewTeamCreateButton {
            get {
                return ResourceManager.GetString("createNewTeamCreateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Team.
        /// </summary>
        public static string createNewTeamCreated1 {
            get {
                return ResourceManager.GetString("createNewTeamCreated1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný was created.
        /// </summary>
        public static string createNewTeamCreated2 {
            get {
                return ResourceManager.GetString("createNewTeamCreated2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Cannot create the team, please try it later.
        /// </summary>
        public static string createNewTeamCreateError {
            get {
                return ResourceManager.GetString("createNewTeamCreateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Team name:.
        /// </summary>
        public static string createNewTeamName {
            get {
                return ResourceManager.GetString("createNewTeamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný You can create new team only after completion of your profile, this button will forward you on page, where you can complete it&quot;.
        /// </summary>
        public static string createNewTeamNotFilledProfile {
            get {
                return ResourceManager.GetString("createNewTeamNotFilledProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Create new team.
        /// </summary>
        public static string createNewTeamTitle {
            get {
                return ResourceManager.GetString("createNewTeamTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný To teams management page.
        /// </summary>
        public static string createNewTeamToManagementButton {
            get {
                return ResourceManager.GetString("createNewTeamToManagementButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný By filling up team name and cliking on button. New team will be created, which can be later managed from team management page.
        /// </summary>
        public static string createNewTeamToolTip {
            get {
                return ResourceManager.GetString("createNewTeamToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Add to team.
        /// </summary>
        public static string playersManagementAddToTeamButton {
            get {
                return ResourceManager.GetString("playersManagementAddToTeamButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Cannot get team with players from database, try it later.
        /// </summary>
        public static string playersManagementCannotLoadPlayers {
            get {
                return ResourceManager.GetString("playersManagementCannotLoadPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Save players of the team.
        /// </summary>
        public static string playersManagementSave {
            get {
                return ResourceManager.GetString("playersManagementSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Cannot save players in team, please try it later.
        /// </summary>
        public static string playersManagementSaveError {
            get {
                return ResourceManager.GetString("playersManagementSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Players were saved.
        /// </summary>
        public static string playersManagementSaveSuccess {
            get {
                return ResourceManager.GetString("playersManagementSaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný You cannot edit players of this team, because it is already registered to tournament.
        /// </summary>
        public static string playersManagementUnable {
            get {
                return ResourceManager.GetString("playersManagementUnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Are you sure, you want to delete this team? This action is to reversible.
        /// </summary>
        public static string teamManagementDeleteDialogDescription {
            get {
                return ResourceManager.GetString("teamManagementDeleteDialogDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Delete team - confirmation.
        /// </summary>
        public static string teamManagementDeleteDialogHeader {
            get {
                return ResourceManager.GetString("teamManagementDeleteDialogHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný No.
        /// </summary>
        public static string teamManagementDeleteNo {
            get {
                return ResourceManager.GetString("teamManagementDeleteNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Delete team.
        /// </summary>
        public static string teamManagementDeleteTeam {
            get {
                return ResourceManager.GetString("teamManagementDeleteTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Yes.
        /// </summary>
        public static string teamManagementDeleteYes {
            get {
                return ResourceManager.GetString("teamManagementDeleteYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný You are not manager of this team, so you cannot do edit actions.
        /// </summary>
        public static string teamManagementNotManager {
            get {
                return ResourceManager.GetString("teamManagementNotManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Players.
        /// </summary>
        public static string teamManagementTabPlayers {
            get {
                return ResourceManager.GetString("teamManagementTabPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Tournaments.
        /// </summary>
        public static string teamManagementTabTournaments {
            get {
                return ResourceManager.GetString("teamManagementTabTournaments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Team management.
        /// </summary>
        public static string teamManagementTitle {
            get {
                return ResourceManager.GetString("teamManagementTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Back to all managed teams.
        /// </summary>
        public static string teamManagementToManagedTeams {
            get {
                return ResourceManager.GetString("teamManagementToManagedTeams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Here is a management page of the selected team. You can edit players by clicking Add to team button and unregister team from tournaments.
        /// </summary>
        public static string teamManagementToolTip {
            get {
                return ResourceManager.GetString("teamManagementToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Cannot load teams, please try it later.
        /// </summary>
        public static string teamsManagementCannotLoadTeams {
            get {
                return ResourceManager.GetString("teamsManagementCannotLoadTeams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Teams management.
        /// </summary>
        public static string teamsManagementTitle {
            get {
                return ResourceManager.GetString("teamsManagementTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Here are teams which you manage, after you click on the team, you will be forwarded to page where to can manage this team. By clicking on Plus button you will create a new team.
        /// </summary>
        public static string teamsManagementToolTip {
            get {
                return ResourceManager.GetString("teamsManagementToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Current and upcoming tournaments.
        /// </summary>
        public static string teamTournamentsCurrent {
            get {
                return ResourceManager.GetString("teamTournamentsCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný No tournament were found.
        /// </summary>
        public static string teamTournamentsManagementNoTournaments {
            get {
                return ResourceManager.GetString("teamTournamentsManagementNoTournaments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Past tournaments.
        /// </summary>
        public static string teamTournamentsPast {
            get {
                return ResourceManager.GetString("teamTournamentsPast", resourceCulture);
            }
        }
    }
}
