//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChessTournamentManager.LanguageAssets.TournamentRegistration {
    using System;
    
    
    /// <summary>
    ///   Třída prostředků se silnými typy pro vyhledávání lokalizovaných řetězců atp.
    /// </summary>
    // Tato třída byla automaticky generována třídou StronglyTypedResourceBuilder
    // pomocí nástroje podobného aplikaci ResGen nebo Visual Studio.
    // Chcete-li přidat nebo odebrat člena, upravte souboru .ResX a pak znovu spusťte aplikaci ResGen
    // s parametrem /str nebo znovu sestavte projekt aplikace Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TournamentRegistrationLabels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TournamentRegistrationLabels() {
        }
        
        /// <summary>
        ///   Vrací instanci ResourceManager uloženou v mezipaměti použitou touto třídou.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChessTournamentManager.LanguageAssets.TournamentRegistration.TournamentRegistrati" +
                            "onLabels", typeof(TournamentRegistrationLabels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Potlačí vlastnost CurrentUICulture aktuálního vlákna pro všechna
        ///   vyhledání prostředků pomocí třídy prostředků se silnými typy.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Back to tournaments page.
        /// </summary>
        public static string backToTournamentsPage {
            get {
                return ResourceManager.GetString("backToTournamentsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Register team.
        /// </summary>
        public static string registerTeamButton {
            get {
                return ResourceManager.GetString("registerTeamButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Cannot get managed teams.
        /// </summary>
        public static string registerTeamCannotGetManagedTeams {
            get {
                return ResourceManager.GetString("registerTeamCannotGetManagedTeams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Cannot register team, please try it later.
        /// </summary>
        public static string registerTeamError {
            get {
                return ResourceManager.GetString("registerTeamError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný You don&apos;t have any teams to register.
        /// </summary>
        public static string registerTeamNoManagedTeams {
            get {
                return ResourceManager.GetString("registerTeamNoManagedTeams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný You can register to tournament only after completion of your profile, this button will forward you on page, where you can complete it.
        /// </summary>
        public static string registrationNotCompletedProfile {
            get {
                return ResourceManager.GetString("registrationNotCompletedProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Team was registered.
        /// </summary>
        public static string registrationTeamWasRegistered {
            get {
                return ResourceManager.GetString("registrationTeamWasRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Tournament registration.
        /// </summary>
        public static string registrationTitle {
            get {
                return ResourceManager.GetString("registrationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný You can register for this tournament.
        /// </summary>
        public static string singleCanRegister {
            get {
                return ResourceManager.GetString("singleCanRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Personal account will be registered.
        /// </summary>
        public static string singleRegisterAccountInfo {
            get {
                return ResourceManager.GetString("singleRegisterAccountInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Register.
        /// </summary>
        public static string singleRegisterButton {
            get {
                return ResourceManager.GetString("singleRegisterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Cannot register this account, please try it later.
        /// </summary>
        public static string singleRegisterError {
            get {
                return ResourceManager.GetString("singleRegisterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný You were successfully registered for this tournament.
        /// </summary>
        public static string singleRegisterSuccess {
            get {
                return ResourceManager.GetString("singleRegisterSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný You can unregister from this tournament. After clicking the button, you will be unregistered.
        /// </summary>
        public static string singleUnregisterCanUnregister {
            get {
                return ResourceManager.GetString("singleUnregisterCanUnregister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný You cannot unregister from this tournanament, tournament has already started.
        /// </summary>
        public static string singleUnregisterWarningHasStarted {
            get {
                return ResourceManager.GetString("singleUnregisterWarningHasStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný You cannot unregister from this tournament, you are not registered.
        /// </summary>
        public static string singleUnregisterWarningNotRegistered {
            get {
                return ResourceManager.GetString("singleUnregisterWarningNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný You cannot unregister from this tournament, registration has already ended. Please contact manager of tournament.
        /// </summary>
        public static string singleUnregisterWarningRegistrationEnded {
            get {
                return ResourceManager.GetString("singleUnregisterWarningRegistrationEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný You cannot register for this tournanament, tournament has started.
        /// </summary>
        public static string singleWarningHasStarted {
            get {
                return ResourceManager.GetString("singleWarningHasStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný You cannot register for this tournament, you are already registered.
        /// </summary>
        public static string singleWarningIsRegistered {
            get {
                return ResourceManager.GetString("singleWarningIsRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný You cannot register for this tournament, there is already maximum number of players.
        /// </summary>
        public static string singleWarningMaximumPlayers {
            get {
                return ResourceManager.GetString("singleWarningMaximumPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný You cannot register for this tournament, registration has already ended.
        /// </summary>
        public static string singleWarningRegistrationClosed {
            get {
                return ResourceManager.GetString("singleWarningRegistrationClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný You cannot register for this tournament, registration is open yet, you can do it from.
        /// </summary>
        public static string singleWarningRegistrationNotOpened {
            get {
                return ResourceManager.GetString("singleWarningRegistrationNotOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Team can be registered for this tournament.
        /// </summary>
        public static string teamCanRegister {
            get {
                return ResourceManager.GetString("teamCanRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný You can unregister from this tournament. After clicking the button, team will be unregistered.
        /// </summary>
        public static string teamUnregisterCanUnregister {
            get {
                return ResourceManager.GetString("teamUnregisterCanUnregister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný You cannot unregister this team from this tournanament, tournament has already started.
        /// </summary>
        public static string teamUnregisterWarningHasStarted {
            get {
                return ResourceManager.GetString("teamUnregisterWarningHasStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný You cannot unregister team from this tournament, it is not registered.
        /// </summary>
        public static string teamUnregisterWarningNotRegistered {
            get {
                return ResourceManager.GetString("teamUnregisterWarningNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný You cannot unregister this team from this tournament, registration has already ended. Please contact manager of tournament.
        /// </summary>
        public static string teamUnregisterWarningRegistrationEnded {
            get {
                return ResourceManager.GetString("teamUnregisterWarningRegistrationEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný You can register teams which have.
        /// </summary>
        public static string teamWarningAboutMaximumNumberOfPlayersPart1 {
            get {
                return ResourceManager.GetString("teamWarningAboutMaximumNumberOfPlayersPart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný players. Teams with different number of players are not visible..
        /// </summary>
        public static string teamWarningAboutMaximumNumberOfPlayersPart2 {
            get {
                return ResourceManager.GetString("teamWarningAboutMaximumNumberOfPlayersPart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný You cannot register this team for this tournament, it is already registered.
        /// </summary>
        public static string teamWarningAlreadyRegistered {
            get {
                return ResourceManager.GetString("teamWarningAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný You cannot register this team for this tournanament, tournament has started.
        /// </summary>
        public static string teamWarningHasStarted {
            get {
                return ResourceManager.GetString("teamWarningHasStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný You cannot register this team for this tournament, there is already maximum number of teams.
        /// </summary>
        public static string teamWarningMaximumTeams {
            get {
                return ResourceManager.GetString("teamWarningMaximumTeams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Player which is in selected team is already in another team in tournament.
        /// </summary>
        public static string teamWarningPlayerInTeamIsInTournament {
            get {
                return ResourceManager.GetString("teamWarningPlayerInTeamIsInTournament", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný You cannot register this team for this tournament, registration has already ended.
        /// </summary>
        public static string teamWarningRegistrationClosed {
            get {
                return ResourceManager.GetString("teamWarningRegistrationClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný You cannot register this team for this tournament, registration is open yet, you can do it from.
        /// </summary>
        public static string teamWarningRegistrationNotOpened {
            get {
                return ResourceManager.GetString("teamWarningRegistrationNotOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný You cannot register this team to tournament, only teams with.
        /// </summary>
        public static string teamWarningWrongSizePart1 {
            get {
                return ResourceManager.GetString("teamWarningWrongSizePart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný player/s are allowed. This team has.
        /// </summary>
        public static string teamWarningWrongSizePart2 {
            get {
                return ResourceManager.GetString("teamWarningWrongSizePart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný player/s.
        /// </summary>
        public static string teamWarningWrongSizePart3 {
            get {
                return ResourceManager.GetString("teamWarningWrongSizePart3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Back to my tournaments.
        /// </summary>
        public static string unregisterSingleBackToTournaments {
            get {
                return ResourceManager.GetString("unregisterSingleBackToTournaments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Cancel registration.
        /// </summary>
        public static string unregisterSingleCancelRegistration {
            get {
                return ResourceManager.GetString("unregisterSingleCancelRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný You were successfuly unregistered from tournament.
        /// </summary>
        public static string unregisterSingleConfirmation {
            get {
                return ResourceManager.GetString("unregisterSingleConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný You cannot unregister from this tournament, only manager of the team can do it, please contact him. If you are the manager, you can unregister team from team management page.
        /// </summary>
        public static string unregisterSingleNotForTeams {
            get {
                return ResourceManager.GetString("unregisterSingleNotForTeams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Cancel registration.
        /// </summary>
        public static string unregisterSingleTitle {
            get {
                return ResourceManager.GetString("unregisterSingleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Back to team management page.
        /// </summary>
        public static string unregistrationTeamBack {
            get {
                return ResourceManager.GetString("unregistrationTeamBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Cancel registration.
        /// </summary>
        public static string unregistrationTeamButton {
            get {
                return ResourceManager.GetString("unregistrationTeamButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Team was unregistered from tournament.
        /// </summary>
        public static string unregistrationTeamConfirmation {
            get {
                return ResourceManager.GetString("unregistrationTeamConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Unregistration.
        /// </summary>
        public static string unregistrationTitleTeam {
            get {
                return ResourceManager.GetString("unregistrationTitleTeam", resourceCulture);
            }
        }
    }
}
