//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChessTournamentManager.LanguageAssets.PlayerService {
    using System;
    
    
    /// <summary>
    ///   Třída prostředků se silnými typy pro vyhledávání lokalizovaných řetězců atp.
    /// </summary>
    // Tato třída byla automaticky generována třídou StronglyTypedResourceBuilder
    // pomocí nástroje podobného aplikaci ResGen nebo Visual Studio.
    // Chcete-li přidat nebo odebrat člena, upravte souboru .ResX a pak znovu spusťte aplikaci ResGen
    // s parametrem /str nebo znovu sestavte projekt aplikace Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PlayerServiceLabels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PlayerServiceLabels() {
        }
        
        /// <summary>
        ///   Vrací instanci ResourceManager uloženou v mezipaměti použitou touto třídou.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChessTournamentManager.LanguageAssets.PlayerService.PlayerServiceLabels", typeof(PlayerServiceLabels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Potlačí vlastnost CurrentUICulture aktuálního vlákna pro všechna
        ///   vyhledání prostředků pomocí třídy prostředků se silnými typy.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Players.
        /// </summary>
        public static string allPlayersPageTitle {
            get {
                return ResourceManager.GetString("allPlayersPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný You can find all acounts which are registered in this program. You can filter based on information about this players. After clicking on magnifying glass icon, their profile will open and you can inspect personal information and see their tournaments.
        /// </summary>
        public static string allPlayersPageToolTip {
            get {
                return ResourceManager.GetString("allPlayersPageToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Edit personal information.
        /// </summary>
        public static string editPlayerInformationButton {
            get {
                return ResourceManager.GetString("editPlayerInformationButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný You can create new tournament only after completion of your profile, this button will forward you to page, where you can complete it.
        /// </summary>
        public static string notCompletedProfileDefaultText {
            get {
                return ResourceManager.GetString("notCompletedProfileDefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Chess club:.
        /// </summary>
        public static string playerClubForm {
            get {
                return ResourceManager.GetString("playerClubForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný First name:.
        /// </summary>
        public static string playerFirstNameForm {
            get {
                return ResourceManager.GetString("playerFirstNameForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Last name:.
        /// </summary>
        public static string playerLastNameForm {
            get {
                return ResourceManager.GetString("playerLastNameForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Cannot get players, please try it later.
        /// </summary>
        public static string playersResultCannotGetPlayers {
            get {
                return ResourceManager.GetString("playersResultCannotGetPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Chess club.
        /// </summary>
        public static string playersResultClub {
            get {
                return ResourceManager.GetString("playersResultClub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný First name.
        /// </summary>
        public static string playersResultFirstName {
            get {
                return ResourceManager.GetString("playersResultFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Last name.
        /// </summary>
        public static string playersResultLastName {
            get {
                return ResourceManager.GetString("playersResultLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný No players were found.
        /// </summary>
        public static string playersResultNoPlayers {
            get {
                return ResourceManager.GetString("playersResultNoPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Search.
        /// </summary>
        public static string searchButton {
            get {
                return ResourceManager.GetString("searchButton", resourceCulture);
            }
        }
    }
}
