//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChessTournamentManager.LanguageAssets.Account {
    using System;
    
    
    /// <summary>
    ///   Třída prostředků se silnými typy pro vyhledávání lokalizovaných řetězců atp.
    /// </summary>
    // Tato třída byla automaticky generována třídou StronglyTypedResourceBuilder
    // pomocí nástroje podobného aplikaci ResGen nebo Visual Studio.
    // Chcete-li přidat nebo odebrat člena, upravte souboru .ResX a pak znovu spusťte aplikaci ResGen
    // s parametrem /str nebo znovu sestavte projekt aplikace Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AccountLabels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AccountLabels() {
        }
        
        /// <summary>
        ///   Vrací instanci ResourceManager uloženou v mezipaměti použitou touto třídou.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChessTournamentManager.LanguageAssets.Account.AccountLabels", typeof(AccountLabels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Potlačí vlastnost CurrentUICulture aktuálního vlákna pro všechna
        ///   vyhledání prostředků pomocí třídy prostředků se silnými typy.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Insert a valid email.
        /// </summary>
        public static string accountEmailNotValid {
            get {
                return ResourceManager.GetString("accountEmailNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Email is required.
        /// </summary>
        public static string accountEmailRequired {
            get {
                return ResourceManager.GetString("accountEmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Password must be at least {2} and at max {1} characters long..
        /// </summary>
        public static string accountPasswordLength {
            get {
                return ResourceManager.GetString("accountPasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Password is required.
        /// </summary>
        public static string accountPasswordRequired {
            get {
                return ResourceManager.GetString("accountPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný New password is required.
        /// </summary>
        public static string accountPasswordRequiredNew {
            get {
                return ResourceManager.GetString("accountPasswordRequiredNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Passwords do not match.
        /// </summary>
        public static string accountPasswordsDontMatch {
            get {
                return ResourceManager.GetString("accountPasswordsDontMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Enter a valid phone number.
        /// </summary>
        public static string accountPhoneNumberValid {
            get {
                return ResourceManager.GetString("accountPhoneNumberValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Confirm password:.
        /// </summary>
        public static string changePasswordConfirm {
            get {
                return ResourceManager.GetString("changePasswordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný New password:.
        /// </summary>
        public static string changePasswordNew {
            get {
                return ResourceManager.GetString("changePasswordNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Old password:.
        /// </summary>
        public static string changePasswordOld {
            get {
                return ResourceManager.GetString("changePasswordOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Change password.
        /// </summary>
        public static string changePasswordTitle {
            get {
                return ResourceManager.GetString("changePasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Update password.
        /// </summary>
        public static string changePasswordUpdate {
            get {
                return ResourceManager.GetString("changePasswordUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Error: It was not possible to send confirmation e-mail.
        /// </summary>
        public static string confirmationEmailSendError {
            get {
                return ResourceManager.GetString("confirmationEmailSendError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Email was confirmed, now you can use this application.
        /// </summary>
        public static string confirmEmailText {
            get {
                return ResourceManager.GetString("confirmEmailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Email confirmation.
        /// </summary>
        public static string confirmEmailTitle {
            get {
                return ResourceManager.GetString("confirmEmailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Error: Invalid login attempt.
        /// </summary>
        public static string invalidLoginWarning {
            get {
                return ResourceManager.GetString("invalidLoginWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Log in.
        /// </summary>
        public static string loginAction {
            get {
                return ResourceManager.GetString("loginAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Email:.
        /// </summary>
        public static string loginEmail {
            get {
                return ResourceManager.GetString("loginEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Forgot your password?.
        /// </summary>
        public static string loginForgotPassword {
            get {
                return ResourceManager.GetString("loginForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Login.
        /// </summary>
        public static string loginHeading {
            get {
                return ResourceManager.GetString("loginHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Use your credentials to login.
        /// </summary>
        public static string loginInfo {
            get {
                return ResourceManager.GetString("loginInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Login.
        /// </summary>
        public static string loginPageTitle {
            get {
                return ResourceManager.GetString("loginPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Password:.
        /// </summary>
        public static string loginPassword {
            get {
                return ResourceManager.GetString("loginPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Register as a new user.
        /// </summary>
        public static string loginRegisterAsNewUser {
            get {
                return ResourceManager.GetString("loginRegisterAsNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Remember me.
        /// </summary>
        public static string loginRembemberMe {
            get {
                return ResourceManager.GetString("loginRembemberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Logout.
        /// </summary>
        public static string logout {
            get {
                return ResourceManager.GetString("logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Change Email.
        /// </summary>
        public static string manageEmailChangeEmail {
            get {
                return ResourceManager.GetString("manageEmailChangeEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Email:.
        /// </summary>
        public static string manageEmailEmail {
            get {
                return ResourceManager.GetString("manageEmailEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Please enter your email..
        /// </summary>
        public static string manageEmailEmailPlaceholder {
            get {
                return ResourceManager.GetString("manageEmailEmailPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Manage email.
        /// </summary>
        public static string manageEmailHeading {
            get {
                return ResourceManager.GetString("manageEmailHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný New email:.
        /// </summary>
        public static string manageEmailNewEmail {
            get {
                return ResourceManager.GetString("manageEmailNewEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Please enter new email..
        /// </summary>
        public static string manageEmailNewEmailPlaceholder {
            get {
                return ResourceManager.GetString("manageEmailNewEmailPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Send verification email.
        /// </summary>
        public static string manageEmailSendVerification {
            get {
                return ResourceManager.GetString("manageEmailSendVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Manage email.
        /// </summary>
        public static string manageEmailTitle {
            get {
                return ResourceManager.GetString("manageEmailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Manage your account.
        /// </summary>
        public static string manageLayoutHeading {
            get {
                return ResourceManager.GetString("manageLayoutHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Change your account settings.
        /// </summary>
        public static string manageLayoutHeading2 {
            get {
                return ResourceManager.GetString("manageLayoutHeading2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Email.
        /// </summary>
        public static string manageMenuEmail {
            get {
                return ResourceManager.GetString("manageMenuEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Password.
        /// </summary>
        public static string manageMenuPassword {
            get {
                return ResourceManager.GetString("manageMenuPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Profile.
        /// </summary>
        public static string manageMenuProfile {
            get {
                return ResourceManager.GetString("manageMenuProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Profile.
        /// </summary>
        public static string manageProfileHeading {
            get {
                return ResourceManager.GetString("manageProfileHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Phone number:.
        /// </summary>
        public static string manageProfilePhonenumber {
            get {
                return ResourceManager.GetString("manageProfilePhonenumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Uložit.
        /// </summary>
        public static string manageProfileSave {
            get {
                return ResourceManager.GetString("manageProfileSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Username:.
        /// </summary>
        public static string manageProfileUsername {
            get {
                return ResourceManager.GetString("manageProfileUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Your password has been changed.
        /// </summary>
        public static string passwordWasChanged {
            get {
                return ResourceManager.GetString("passwordWasChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Your profile has been updated.
        /// </summary>
        public static string profileUpdated {
            get {
                return ResourceManager.GetString("profileUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Register.
        /// </summary>
        public static string registerAction {
            get {
                return ResourceManager.GetString("registerAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Please check your email..
        /// </summary>
        public static string registerConfirmEmail {
            get {
                return ResourceManager.GetString("registerConfirmEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Confirm your email by clicking on the link in the email.
        /// </summary>
        public static string registerConfirmEmailLink {
            get {
                return ResourceManager.GetString("registerConfirmEmailLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Registration confirm.
        /// </summary>
        public static string registerConfirmHeading {
            get {
                return ResourceManager.GetString("registerConfirmHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Confirm password:.
        /// </summary>
        public static string registerConfirmPassword {
            get {
                return ResourceManager.GetString("registerConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Registration confirm.
        /// </summary>
        public static string registerConfirmTitle {
            get {
                return ResourceManager.GetString("registerConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Create new account.
        /// </summary>
        public static string registerCreateNewAccountInfo {
            get {
                return ResourceManager.GetString("registerCreateNewAccountInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Email:.
        /// </summary>
        public static string registerEmail {
            get {
                return ResourceManager.GetString("registerEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Confirm your email from TourMan app.
        /// </summary>
        public static string registerEmailSubject {
            get {
                return ResourceManager.GetString("registerEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Confirm your email by clicking on this link: .
        /// </summary>
        public static string registerEmailText {
            get {
                return ResourceManager.GetString("registerEmailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Register.
        /// </summary>
        public static string registerHeading {
            get {
                return ResourceManager.GetString("registerHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Register.
        /// </summary>
        public static string registerPageTitle {
            get {
                return ResourceManager.GetString("registerPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Password:.
        /// </summary>
        public static string registerPassword {
            get {
                return ResourceManager.GetString("registerPassword", resourceCulture);
            }
        }
    }
}
